name: Test

on:
  push:
    branches: [ "master" ]

permissions:
  contents: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install ZSH
        run: |-
          sudo apt update
          sudo apt install zsh -y

      - name: Run Tests
        run: ./test/git-open.test.zsh
  release:
    needs:
      - test
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          release-type: simple

