name: Test

on:
  push:
    branches: ["develop" ]
  pull_request:
    branches: [ "master", "develop" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install ZSH
        run: |-
          sudo apt update
          sudo apt install zsh -y

      - name: Run Tests
        run: make test
